ports:
- port: 19870
  onOpen: open-preview

tasks:
- before: >
    cd /workspace/uiw/
  init: npm install
  command: npm run bootstrap &&
    npm run b:uiw &&
    npm run b:css &&
    npm run type

- before: >
    export DEV_HOST=$(gp url 19870)
  openMode: split-right
  command: npm run website
