name: Build uiw
on:
  push:
    branches:
      - master
jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - run: npm install
    - run: npm run bootstrap
    - run: npm run build
    - run: npm run bundle
    - run: npm run coverage

    # - name: Deploy
    #   uses: peaceiris/actions-gh-pages@v3
    #   with:
    #     deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY_WEBSITE }}
    #     external_repository: uiwjs/uiwjs.github.io
    #     publish_branch: master
    #     publish_dir: ./website/uiw/build
    # - name: Install SSH Client 🔑
    #   uses: webfactory/ssh-agent@v0.2.0
    #   with:
    #     ssh-private-key: ${{ secrets.ACTIONS_DEPLOY_KEY_WEBSITE }}

    # - name: Deploy 🚀
    #   uses: JamesIves/github-pages-deploy-action@releases/v3
    #   with:
    #     SSH: true
    #     BRANCH: master # The branch the action should deploy to.
    #     FOLDER: website/uiw/build # The folder the action should deploy.
    #     REPOSITORY_NAME: uiwjs/uiwjs.github.io

    - name: Deploy to uiwjs.github.io
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN_UIW }}
        publish_dir: ./website/uiw/build
        publish_branch: master
        external_repository: uiwjs/uiwjs.github.io

    - name: Build and Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_branch: gh-pages
        publish_dir: ./website/uiw/build

    - name: Sync to Gitee
      run: |
        mirror() {
          git clone "https://github.com/$1/$2"
          cd "$2"
          git remote add gitee "https://jaywcjlove:${{ secrets.GITEE_TOKEN }}@gitee.com/uiw/$2.git"
          git remote set-head origin -d
          git push gitee --prune +refs/remotes/origin/*:refs/heads/* +refs/tags/*:refs/tags/*
          cd ..
        }
        mirror uiwjs uiw